name: Deploy to Google Play 

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download AAB from GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p build_output
          gh release download 1.0.0 \
            --pattern "com.hydronixcascado.arhydcas.aab" \
            --dir build_output

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Fastlane uploading to Open Test
        env:
          GOOGLE_PLAY_JSON_KEYS: ${{ secrets.GOOGLE_PLAY_JSON_KEYS }}
        run: |
          export GOOGLE_PLAY_JSON_KEYS="$(echo "$GOOGLE_PLAY_JSON_KEYS")"
          fastlane android upload_to_open
